import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";
import { layoutStyle } from "./style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next My Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <nav className={layoutStyle.navStyle}>
            <Link
              className={layoutStyle.LinkStyle}
              href="/"
            >
              About
            </Link>
            <Link
              className={layoutStyle.LinkStyle}
              href="/report"
            >
              Report
            </Link>
            <Link
              className={layoutStyle.LinkStyle}
              href="/todoCSR"
            >
              Todos-CSR
            </Link>
            <Link
              className={layoutStyle.LinkStyle}
              href="/todoSSR"
            >
              Todos-SSR
            </Link>
          </nav>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
