import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import QueryProvider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next My Todo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <nav>
            <Link href="/">About</Link>
            <Link href="/report">Report</Link>
            <Link href="/todoCSR">Todos-CSR</Link>
            <Link href="/todoSSR">Todos-SSR</Link>
          </nav>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
